RuneApp/Main.cs

Quick fix of something that was bugging me

Update UI after removing a or all loadouts

---

RuneApp/Main.cs
RuneApp/Program.cs
RuneClasses/Management/Loadout.cs

Fixes #68 by adding and using an `Unlock` method on the current/previous loadout.

Unlock current loadout

---

RuneApp/LeaderType.cs

Uses current values in Swarfarm.  Resolves #61

Updates Leader Skill Table

---

RuneApp/Program.cs

Unlock Current Loadout (not in-game runes)

---

RuneApp/Main.Designer.cs

This fixes whitespace without changing anything about the Main form so deltas and merges should work going forward.

Trivial Whitespace PR

---

RuneApp/Main.cs
RuneApp/Program.cs

Resolves #79 by clearing the "Progress" panel on the build column if the associated loadout is removed.

Clear Progress on Loadout Removal

---

RuneApp/Main.Designer.cs
RuneApp/Main.cs
RuneApp/Main.resx
RuneApp/Program.cs

For some reason git closed #87 but this is the rebased and hand-cleaned version for this, resolving #86.

hand-cleaned changes to Build Runner

---

RuneClasses/swar/MultiplierBase.cs

add `RIDER_SPEED` to support beast riders

---

RuneApp/Main.cs

I modified the existing code to support lv20 buildings.  I haven't spot checked every skill to make sure it works.  Fixes #115

Draft building logic

---

RuneApp/LeaderType.cs

Add accuracy leader types

---

RuneApp/Create.cs
RuneApp/Main.Functions.cs
RuneApp/Main.cs
RuneApp/Program.Builds.cs
RuneApp/Program.Saves.cs
RuneApp/Program.cs
RuneClasses/BuildProcessing/Build.Old.cs
RuneClasses/BuildProcessing/Build.cs
RuneClasses/BuildProcessing/BuildBitMatcherBaseRunner.cs
RuneClasses/BuildProcessing/BuildRunner.cs
RuneClasses/BuildProcessing/BuildSettings.cs
RuneClasses/Management/ILoadout.cs
RuneClasses/Management/Loadout.cs
RuneClasses/swar/Guild.cs
RuneClasses/swar/Save.cs

For now, default to the dungeon bonus (since Tricaru tuning is most likely).  We'll eventually need to add a UI item to control this default.

Pass guild bonuses around

---

RuneClasses/swar/MultiplierBase.cs

Adds support for `ALIVE_RATE` and fixes handling of `RIDER_SPEED`

---

RuneClasses/swar/MultiplierBase.cs

Needed to handle new monster stats more places.  Revert rider speed "fix" since we don't have access to the rider.

New Attribute Fixes

---

RuneClasses/swar/Rune.Properties.cs

fix handling of 4-set required, allow broken, 4-set include. Closes #150.

Fixes Set Filter per Issue 150

---

RuneApp/Main.cs
RuneClasses/swar/Guild.cs

closes #173 by adding default (0) for guild bonuses
closes #174 by changing the way empty slots are calculated

Quick fixes

---

.gitmodules

cleanup submodule

---

RuneApp/LoadSaveDialogue.Designer.cs
RuneApp/LoadSaveDialogue.cs
RuneApp/Main.Functions.cs
RuneApp/Main.cs
RuneApp/Program.Saves.cs
RuneApp/Program.cs
RuneAppTests/GithubIssues.cs
RuneOptim.sln
RuneService/RuneService.csproj

Clean up some dialogs and associated code to make the initial experience somewhat cleaner.

Clean up some dialogs and associated code.

---

RuneApp/Main.Functions.cs
RuneApp/Main.Loads.cs
RuneApp/Main.cs
RuneApp/Main.resx
RuneApp/Program.Saves.cs
RuneApp/Program.cs
RuneClasses/BuildProcessing/Build.Old.cs
RuneClasses/Management/Loadout.cs
RuneClasses/swar/Rune.cs

Mostly documentation and refactor, but got distracted and closed #188 and closed #156 at the same time.

Documentation and refactoring.  Also closes #188 and closes #156.

---

RuneApp/Program.cs

Removed `Close()` which doesn't appear to do anything

---

RuneApp/Main.Model.cs
RuneApp/Main.cs
version.txt

Use github API to detect upgrades

---

RuneApp/Main.Designer.cs
RuneApp/Main.cs
RuneApp/Program.Builds.cs
RuneClasses/BuildProcessing/Build.cs

Significant reorganization to key files to group together methods related to the same data/UI elements.

Reorganize by Function and Document

---

RuneClasses/BuildProcessing/Build.Old.cs
RuneClasses/BuildProcessing/Enums.cs
RuneClasses/swar/Stats.cs

closes #206 by adjusting the comparison logic

Fix comparison logic for ExtraValues attributes

---

RuneApp/Create.Functions.cs
RuneApp/Create.cs
RuneApp/Generate.cs
RuneApp/GenerateLive.cs
RuneApp/Properties/AssemblyInfo.cs
RuneApp/RuneApp.csproj
RuneApp/packages.config
RuneClasses/BuildProcessing/Build.Old.cs
RuneClasses/BuildProcessing/Build.cs
RuneClasses/BuildProcessing/BuildBitMatcherBaseRunner.cs
RuneClasses/BuildProcessing/BuildFourSetBrokenFast.cs
RuneClasses/BuildProcessing/BuildRunner.cs
RuneClasses/Management/ILoadout.cs
RuneClasses/Management/Loadout.cs
RuneClasses/RuneClasses.csproj
RuneClasses/packages.config
RuneClasses/swar/Guild.cs
RuneClasses/swar/Rune.Extra.cs
RuneClasses/swar/Rune.Properties.cs
RuneClasses/swar/Rune.cs
RuneClassesTests/RuneTests.cs
plugins/RiftTrackerPlugin/RiftTrackerPlugin.cs

While PR #200 made the rune filtering logic more accurate, it had the unexpected side-effect of causing high quality builds to disappear (see #205).  This PR accelerated #197 in the hopes that it would fix #205.  During that refactor, a bug was discovered in the filtering logic (#209).  This PR closes #197 and fixes the bug which closes #209 and thus closes #205.

Optimizer Refactor and Bug Fixes

---

RuneApp/Create.Functions.cs
RuneApp/Create.cs
RuneApp/Generate.cs
RuneApp/GenerateLive.cs
RuneApp/InternalServer/PageRenderers/CssRenderer.cs
RuneClasses/BuildProcessing/Build.Old.cs
RuneClasses/BuildProcessing/Build.cs
RuneClasses/BuildProcessing/BuildBitMatcherBaseRunner.cs
RuneClasses/BuildProcessing/BuildFourSetBrokenFast.cs
RuneClasses/Management/Loadout.cs
RuneClasses/swar/Guild.cs
RuneClasses/swar/Rune.Extra.cs
RuneClasses/swar/Rune.Properties.cs
RuneClasses/swar/Rune.cs

Also, refactor some methods to more logical places.

Bug fixes in new optimization logic.  

---

RuneApp/Create.Functions.cs
RuneClasses/BuildProcessing/Build.cs

Verified that the dial goes to zeros if I put a speed one tick higher than the highest set (as generated by the optimizer).

More Bug Fixes to new Optimizer Logic

---

RuneClasses/BuildProcessing/Build.cs
RuneClasses/RuneClasses.csproj
RuneClasses/swar/Attrs.cs
RuneClasses/swar/Guild.cs
RuneClasses/swar/Rune.Properties.cs
RuneClasses/swar/Stats.cs

The behavior of `Stats` was creating tons of issues accumulating bonuses.  `Attrs` was created as a pure accumulator.  Exposed additional needs in the filtering cycles.

More Optimization Fixes

---

RuneApp/Main.Functions.cs
RuneApp/Main.cs
RuneApp/Program.Saves.cs
RuneApp/Properties/AssemblyInfo.cs
RuneClasses/BuildProcessing/Build.Old.cs
RuneClasses/BuildProcessing/Build.cs
RuneClasses/Management/Loadout.cs
RuneClasses/RuneClasses.csproj
RuneClasses/swar/Monster.cs
RuneClasses/swar/RuneLock.cs
RuneClasses/swar/Save.cs

closes #117.  closes #221. refactoring, renaming, and other cleanup.

0.8.0 bug fixes
